[package]
name = "parallel"
version = "0.1.0"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]
license = "MIT"
publish = false

[dependencies]
env_logger = "0.5.13"
log = "0.4.5"
num_cpus = "1"
rand = "0.5.5"
